/*
 * pwix:modal/src/client/js/constants.js
 */

MODAL_BTN_OK = 'MODAL_BTN_OK';
MODAL_BTN_CANCEL = 'MODAL_BTN_CANCEL';
MODAL_BTN_CLOSE = 'MODAL_BTN_CLOSE';
MODAL_BTN_SAVE = 'MODAL_BTN_SAVE';
MODAL_BTN_YES = 'MODAL_BTN_YES';
MODAL_BTN_NO = 'MODAL_BTN_NO';
